server:
  port: 8082
spring:
  application:
    name: queen-passport-bff

passport-inspector:
  client:
    url: http://localhost:8080
    merchant-id: 550e8400-e29b-41d4-a716-446655440000
    token: bff-internal-token